package warehouse.model

case class MainData(
                     count_point_id: Int,
                     direction_of_travel: String,
                     year: String,
                     count_date: String,
                     hour: String,
                     local_authoirty_ons_code: String,
                     road_name: String,
                     road_category: String,
                     road_type: String,
                     start_junction_road_name: String,
                     end_junction_road_name: String,
                     easting: String,
                     northing: String,
                     latitude: String,
                     longitude: String,
                     link_length_km: String,
                     link_length_miles: String,
                     pedal_cycles: Int,
                     two_wheeled_motor_vehicles: Int,
                     cars_and_taxis: Int,
                     buses_and_coaches: Int,
                     lgvs: Int,
                     hgvs_2_rigid_axle: Int,
                     hgvs_3_rigid_axle: Int,
                     hgvs_4_or_more_rigid_axle: Int,
                     hgvs_3_or_4_articulated_axle: Int,
                     hgvs_5_articulated_axle: Int,
                     hgvs_6_articulated_axle: Int,
                     all_hgvs: Int,
                     all_motor_vehicles: Int
                   )
